# Generated by Django 4.0.5 on 2022-06-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20, verbose_name='Usuario')),
                ('email', models.CharField(max_length=40, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=30, verbose_name='Contraseña')),
            ],
        ),
    ]
